---

- name: Install Perl dependencies with CPANM...
  become: true
  community.general.cpanm:
    name: '{{ item }}'
  loop:
    - Net::DBus
    - Dotenv
    - File::Which
    - Audio::Play::MPG123
    - LWP::Simple
    - JSON
    - JSON::MaybeXS
  tags: lucia

...
