---

- name: Configure services...
  ansible.builtin.template:
    src: templates/{{ item }}_config.j2
    dest: '{{ systemd_user_config }}/systemd/user/{{ item }}.service'
    mode: 0700
  loop:
    - x_start
    - lucia
  tags: daemon

- name: Reload configuration from SystemD...
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
  tags: daemon

...
