---

- name: Enable services...
  ansible.builtin.systemd:
    name: '{{ item }}'
    scope: user
    enabled: true
  loop:
    - lucia
    - x_start
  tags: daemon

- name: Start services...
  ansible.builtin.systemd:
    name: '{{ item }}'
    scope: user
    state: started
  loop:
    - x_start
    - lucia
  tags: daemon

...
